# Generated by Django 4.2.30 on 2026-04-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('chosenType', models.CharField(max_length=50)),
                ('chosenDate', models.DateField()),
                ('chosenTime', models.CharField(max_length=5)),
                ('allPhoto', models.BooleanField(default=False)),
                ('chosenCountPeople', models.PositiveIntegerField()),
                ('chosenReportHours', models.PositiveIntegerField()),
                ('extraInfo', models.TextField(blank=True)),
                ('price', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
