# Generated by Django 4.2.30 on 2026-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backLeraPhoto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=20),
            preserve_default=False,
        ),
    ]
