# Generated by Django 4.2.30 on 2026-04-18 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backLeraPhoto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='allPhoto',
            new_name='all_photo',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='chosenDate',
            new_name='chosen_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='chosenTime',
            new_name='chosen_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='extraInfo',
            new_name='extra_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='chosenCountPeople',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='chosenReportHours',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='chosenType',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='chosen_count_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='chosen_report_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='manager_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='backLeraPhoto.bookingcategory'),
        ),
    ]
