# Generated by Django 4.2.30 on 2026-04-23 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backLeraPhoto', '0002_bookingcategory_rename_allphoto_booking_all_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backLeraPhoto.booking')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
